version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 0
      PGID: 0
    ports:
      - 3000:3000
    volumes:
      - ./images:/app/public/images
      - ./icons:/app/public/icons
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
