---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Datacenter:
    - Pansiere:
        icon: proxmox.png
        href: https://192.168.1.98:8006/
        description: Servidor de infraestrutura
        ping: 192.168.1.98:8006
        siteMonitor: https://pansiere.cc/

    - pm.pansiere:
        icon: proxmox.png
        href: https://10.0.0.1:8006/
        description: Servidor Proxmox
        ping: 10.0.0.1:8006
        siteMonitor: https://pm.pansiere.com/

- Infraestrutura:
    - PfSense:
        icon: pfsense
        href: https://192.168.1.98:8006/
        description: Firewall/Roteador Virtual
        ping: 192.168.1.98:8006
        siteMonitor: https://pansiere.cc/

    - Nginx Proxy Manager:
        icon: nginx.png
        href: https://proxy.pansiere.cc/
        description: Firewall/Roteador Virtual
        ping: https://proxy.pansiere.cc
        siteMonitor: https://proxy.pansiere.cc/

    - Pi-hole:
        icon: pi-hole.png
        href: https://pihole.pansiere.cc/admin
        description: Servidor DHCP e DNS
        ping: 10.1.1.1:80
        siteMonitor: https://pihole.pansiere.cc/

    - Uptime-Kuma:
        icon: uptime-kuma.png
        href: https://192.168.1.98:8006/
        description: Serviço de disponibilidade
        ping: 192.168.1.98:8006
        siteMonitor: https://pansiere.cc/

- Reposit  rios:
    - Automations:
        icon: github.png
        href: https://github.com/pansiere/Automations

    - Docker:
        icon: github.png
        href: https://github.com/pansiere/Docker

    - PHP:
        icon: github.png
        href: https://github.com/pansiere/php

    - Others:
        icon: github.png
        href: https://github.com/pansiere/php

    - HTML:
        icon: github.png
        href: https://github.com/pansiere/others

- Aplicações:
    - Wazuh:
        icon: wazuh
        href: https://wazuh.pansiere.com
        description: Security, Information and Event Management
        ping: 10.0.0.10:80
        siteMonitor: https://wazuh.pansiere.com

    - openmediavault:
        icon: openmediavault
        href: http://10.0.0.10
        description: Servidor de arquivos
        ping: 10.0.0.10:80
        siteMonitor: https:/omv.pansiere.cc

    - VSCode Server:
        icon: vscode
        href: https://vscode.pansiere.com
        description: Servidor de arquivos
        ping: https://vscode.pansiere.com
        siteMonitor: https://vscode.pansiere.com
