---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: Home-Pansiere
target: _self
background: /images/background.png
theme: dark
color: stone
